name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # Setup PNPM
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.19.0

      # Install dependencies
      - name: Install dependencies
        run: pnpm i

      # Build with Astro Deno
      - name: Build Astro
        run: pnpm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: dpmland
          entrypoint: server/entry.mjs
          root: dist
